### ISSUE TITLE
Fastboot fails

### ISSUE THREAD

**Issue by ewoutp** [san650/ember-web-app#5] opened 2016-11-08 08:33 UTC
I've tried this module in combination with Ember fastboot, but I get errors in fastboot (that I do not get without this module).

I've only installed this module (`ember install..`) and not done anything else.

**Comment by san650** [comment] 2016-11-08 12:48
Thanks for reporting the issue @ewoutp. The addon is still a work in progress but the early feedback is welcome.

I'll try to tackle fastboot support asap.

**Comment by ewoutp** [comment] 2016-11-08 12:49
Great!.

I was looking for a plugin like this, so I'm happy to test stuff.

**Comment by san650** [comment] 2016-12-11 23:16
@ewoutp I was trying to reproduce this error but it seems that everything works fine with the latest version.

Can you try to reproduce the error? Can you also provide more info about the error?

Thanks!

**Comment by san650** [comment] 2016-12-14 23:04
I couldn't reproduce the issue so I'm closing it for now.

@ewoutp please, feel free to open it again if you can reproduce the issue.

**Comment by ewoutp** [comment] 2016-12-15 08:22
I'll test it as soon as I have a little time for it.
Thx!

**Comment by teddyzeenny** [comment] 2016-12-15 11:36
Hi @san650. I also couldn't use this addon with fastboot. I was able to track down the problem:

- This addon adds `json` to the `replaceExtensions` array in broccoli-asset-rev's fingerprint options (to fingerprint the assets in `manifest.json`).
- Fastboot creates a file called `fastbootAssetMap.json` in `dist` to map the original asset URLs to the newly fingerprinted ones.
- Since we are now fingerprinting assets in `json` files (because of step 1) `fastbootAssetMap.json`'s asset URLs are being fingerprinted as well (which makes the asset map useless since it's now mapping fingerprinted assets to fingerprinted assets). 

In order to reproduce this you will need to be using fastboot with the production build (so that fingerprinting is enabled).

**Comment by teddyzeenny** [comment] 2016-12-15 11:38
I just found a related issue https://github.com/rickharrison/broccoli-asset-rev/issues/91.

**Comment by san650** [comment] 2016-12-15 12:53
Thanks @ewoutp and @teddyzeenny ! I'll open the issue again.

**Comment by teddyzeenny** [comment] 2016-12-15 15:30
I think adding `json` to `replaceExtensions` globally is going to have unexpected side effects not limited to just fastboot.

**Comment by san650** [comment] 2016-12-15 16:37
I was playing with the `ignore` option of `broccoli-asset-rev`, the option is forwarded to `broccoli-asset-write` and allows you to ignore the given paths. It kind of works but it solves only the `fastbootAssetMap.json` case.

You're right about that adding `json` to `replaceExtensions` could break other addons/apps.

Another approach I'm trying right now is to rename the `manifest.json` file to `manifest.x.json` and adding `x.json` to `replaceExtensions`. The idea is to rename the `manifest.x.json` file to `manifest.json` after `broccoli-asset-rev` runs. It's just an experiment but it might be a plausible solution (maybe we can invent a different extension name but `x.json` works for now).

@teddyzeenny What do you think?

**Comment by san650** [comment] 2016-12-15 16:41
@teddyzeenny I've opened an experimental PR with the `ignore` solution. See #19 

Do you want to work on this issue? I was just doing a quick experiment.

**Comment by teddyzeenny** [comment] 2016-12-15 16:55
@san650 `.x.json` approach is the workaround I did in my app :) Used: `manifest.ember-web-app.json` and renamed it back to `manifest.json` in `postBuild` hook.

**Comment by san650** [comment] 2016-12-15 16:58
@teddyzeenny Do you want to open a PR with this solution? I like the `ember-web-app.json` name for the extension.

If not, I'll try to implement it later this week.

Thanks for helping triaging this bug!

**Comment by teddyzeenny** [comment] 2016-12-15 17:02
@san650 sure I can open on a PR. Would you like to keep it as `manifest.ember-web-app.json` and update the `<link rel="manifest">` href, or rename it to `manifest.json` in `postBuild`?

**Comment by san650** [comment] 2016-12-15 17:06
I prefer to rename it to `manifest.json` in `postBuild`. I would like to make the name configurable in the future so we'll need the `postBuild` step either way.

**Closed** 2016-12-15 19:40 UTC
Labels: bug

**Comment by san650** [comment] 2016-12-15 19:44
Thanks @teddyzeenny for fixing the bug! 👏

**Comment by san650** [comment] 2016-12-15 19:50
Released https://github.com/san650/ember-web-app/releases/tag/v1.0.4
